$('.owl-carousel').owlCarousel({
    loop:true,
    margin:3,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:3
        }
    },
    autoplay:true,
    autoplayTimeout:6000,
    autoplayHoverPause:false,
})