$('.owl-carousel').owlCarousel({
    loop:true,
    margin:0,
    nav:false,
    autoWidth:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:2
        },
        1600:{
            items:3
        }
    },
    autoplay:true,
    autoplayTimeout:6000,
    autoplayHoverPause:false,
})